### ISSUE TITLE
Monorepo setup - Error: [nuqs] nuqs requires an adapter to work with your framework.

### ISSUE THREAD

**Issue by janglad** [47ng/nuqs#798]
## Context

What's your version of `nuqs`?
2.2.3

```
"nuqs": "^2.2.3",
```
What framework are you using?

Next JS 

- ✅/❌ Next.js (app router) (with React Compiler turned on, using Turbopack in dev but issue also occurs during build)

Which version of your framework are you using?

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:51:54 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 22.10.0
  npm: 10.9.0
  Yarn: 1.22.22
  pnpm: 9.12.2
Relevant Packages:
  next: 15.0.3 // There is a newer version (15.0.4) available, upgrade recommended!
  eslint-config-next: N/A
  react: 19.0.0-rc-fb9a90fa48-20240614
  react-dom: 19.0.0-rc-fb9a90fa48-20240614
  typescript: 5.6.3
Next.js Config:
```

## Description

We have a turbo pnpm monorepo with next js. Nuqs has been acting up for a bit, erroring out and saying that the adapter isn't installed. This is however the case (and the adapter gets resolved fine). In the past this was fixed by uninstalling nuqs from the pacakges that used it and adding it again, however this now also isn't working. Below is relevant information about nuqs in the pnpm-lock

```
importers:
  apps/web:
    dependencies:
      ...
      nuqs:
        specifier: ^2.2.3
        version: 2.2.3(next@15.0.3(@babel/core@7.25.2)(@opentelemetry/api@1.9.0)(@playwright/test@1.48.2)(babel-plugin-react-compiler@19.0.0-beta-8a03594-20241020)(react-dom@19.0.0-rc-fb9a90fa48-20240614(react@19.0.0-rc-fb9a90fa48-20240614))(react@19.0.0-rc-fb9a90fa48-20240614))(react@19.0.0-rc-fb9a90fa48-20240614)
```

```
importers:
  packages/some-package-that-is-used-in-web:
    dependencies:
      ...
      nuqs:
        specifier: ^2.2.3
        version: 2.2.3(next@15.0.3(@opentelemetry/api@1.9.0)(@playwright/test@1.48.2)(react-dom@19.0.0-rc-fb9a90fa48-20240614(react@19.0.0-rc-fb9a90fa48-20240614))(react@19.0.0-rc-fb9a90fa48-20240614))(react@19.0.0-rc-fb9a90fa48-20240614)
```

```
packages:
   ...
  nuqs@2.2.3:
    resolution: {integrity: sha512-nMCcUW06KSqEXA0xp+LiRqDpIE59BVYbjZLe0HUisJAlswfihHYSsAjYTzV0lcE1thfh8uh+LqUHGdQ8qq8rfA==}
    peerDependencies:
      '@remix-run/react': '>=2'
      next: '>=14.2.0'
      react: ^19.0.0-rc
      react-router-dom: '>=6'
    peerDependenciesMeta:
      '@remix-run/react':
        optional: true
      next:
        optional: true
      react-router-dom:
        optional: true
```

```
snapshots:
    nuqs@2.2.3(next@15.0.3(@babel/core@7.25.2)(@opentelemetry/api@1.9.0)(@playwright/test@1.48.2)(babel-plugin-react-compiler@19.0.0-beta-8a03594-20241020)(react-dom@19.0.0-rc-fb9a90fa48-20240614(react@19.0.0-rc-fb9a90fa48-20240614))(react@19.0.0-rc-fb9a90fa48-20240614))(react@19.0.0-rc-fb9a90fa48-20240614):
    dependencies:
      mitt: 3.0.1
      react: 19.0.0-rc-fb9a90fa48-20240614
    optionalDependencies:
      next: 15.0.3(@babel/core@7.25.2)(@opentelemetry/api@1.9.0)(@playwright/test@1.48.2)(babel-plugin-react-compiler@19.0.0-beta-8a03594-20241020)(react-dom@19.0.0-rc-fb9a90fa48-20240614(react@19.0.0-rc-fb9a90fa48-20240614))(react@19.0.0-rc-fb9a90fa48-20240614)

  nuqs@2.2.3(next@15.0.3(@opentelemetry/api@1.9.0)(@playwright/test@1.48.2)(react-dom@19.0.0-rc-fb9a90fa48-20240614(react@19.0.0-rc-fb9a90fa48-20240614))(react@19.0.0-rc-fb9a90fa48-20240614))(react@19.0.0-rc-fb9a90fa48-20240614):
    dependencies:
      mitt: 3.0.1
      react: 19.0.0-rc-fb9a90fa48-20240614
    optionalDependencies:
      next: 15.0.3(@opentelemetry/api@1.9.0)(@playwright/test@1.48.2)(react-dom@19.0.0-rc-fb9a90fa48-20240614(react@19.0.0-rc-fb9a90fa48-20240614))(react@19.0.0-rc-fb9a90fa48-20240614)
```

The thing that jumps out to me is the mismatch in the long string of seemingly next specific identifiers (babel/core...). I'm not sure if this maters, and if it does if this is an issue on the Nuqs side or on the pnpm side (or ours!).

**Comment by janglad** [comment]
As an update, got this resolved by manually editing the pnpm-lock and removing the first entry under snapshots in the post above. Again not sure if this is nuqs, pnpm or something on our end. FWIW uninstalling did remove every nuqs reference in the lock, adding it added both of those automatically.

**Comment by janglad** [comment]
> Are you importing the adapter and using the hooks that cause the error in different packages by any chance?
> 
> I think this is what would cause the issue: different instances of the module being loaded in memory by different parts of your monorepo setup, causing the React Context reference to differ, and making nuqs hooks unaware of the adapter/provider which is under a different reference.
> 
> Since manually editing the lockfile isn't very robust, have you tried using [pnpm overrides](https://pnpm.io/package_json#pnpmoverrides) yet? It feels like it could be a good candidate for pinning the same nuqs module reference across all consuming packages.

This is indeed what I'm doing, and that makes a lot of sense. I'll look into that!

**Comment by franky47** [comment]
@janglad have you had any luck in making it work?

**Comment by janglad** [comment]
> @janglad have you had any luck in making it work?

I actually haven't sadly, using the overwrites you mentioned does not fix the issue when using a specifier like "2.2.3" (that version was shared between the versions either way), and using the exact one used in the lock doesn't work either.

It is working again right now due to the manual lock edit but yeah indeed just very brittle. I guess another solution would he creating a single package that just has Nuqs, and using it across the repo from there?

**Comment by franky47** [comment]
Thanks for the feedback. Would you be able to create a minimal reproduction repo?

I'm pretty sure there's got to be a pnpm config that causes/explains this behaviour, as the root of the issue is in the lock resolution, it should not require a userland fix.

**Comment by Philitician** [comment]
We had the same issue with our monorepo when importing components using nuqs from a turborepo package. The error went away when we included both react and nextjs as dependencies in the turborepo package. Not sure if this is the best way to solve it, but seemed to do the trick for us without fiddling with the pnpm-lock file.

**Comment by janglad** [comment]
> We had the same issue with our monorepo when importing components using nuqs from a turborepo package. The error went away when we included both react and nextjs as dependencies in the turborepo package. Not sure if this is the best way to solve it, but seemed to do the trick for us without fiddling with the pnpm-lock file.

The package in question already has deps on both of those so sadly doesn't seem like a reliable way to solve it

**Comment by BjoernRave** [comment]
also a little bit hacky, but you can try to re-export everything from nuqs from your shared package and then only import from that file, so there is only one dep on nuqs in the shared package

**Comment by ktisakib** [comment]
in my case sometimes it appears it doesn't.
I am using monorepo packages and nuqs is used in one of my packages

**Comment by crownofapollo** [comment]
In case anyone else runs into this with turborepo, I ended up installing nuqs at the root of the repo so the same dependency is referenced in every package. Not ideal, but it worked for me.

**Comment by franky47** [comment]
The root cause of this issue is described in react.dev in the [useContext troubleshooting](https://react.dev/reference/react/useContext#my-component-doesnt-see-the-value-from-my-provider) section:

> You might be running into some build issue with your tooling that causes `SomeContext` as seen from the providing component and `SomeContext` as seen by the reading component to be two different objects. This can happen if you use symlinks, for example. You can verify this by assigning them to globals like `window.SomeContext1` and `window.SomeContext2` and then checking whether `window.SomeContext1 === window.SomeContext2` in the console. If they’re not the same, fix that issue on the build tool level.

The `NuqsAdapter` is an internal context provider, so the `window.SomeContext{1,2}` debug tip might not work straight away, and would need a little digging into the nuqs bundled code.

If someone is feeling adventurous, here's the steps to test if the context reference had already been created:

1. Go to `node_modules/nuqs/dist/adapters/{path/to/your/adapter}.js`
2. Look for the chunk where `createAdapterProvider` is exported from, and open it (eg: `node_modules/nuqs/dist/chunk-DASHEO2X.js` for version 2.3.1)
3. After the line `context.displayName = "NuqsAdapterContext";`, insert the following code:

```js
if (process.env.NODE_ENV === 'development') {
  if (typeof window !== 'undefined') {
    if (
      window.__NuqsAdapterContext !== undefined &&
      window.__NuqsAdapterContext !== context
    ) {
      console.error('[nuqs] Adapter context already exists in the global scope')
    }
    window.__NuqsAdapterContext = context
  }
}
```
4. Run your app in development mode and see if an error comes up.

**Comment by franky47** [comment]
I added this in a preview PR, to make it a bit user-friendlier. Steps are now:

1. Install the preview:
```
pnpm add https://pkg.pr.new/nuqs@861
```
2. Enable [debugging](https://nuqs.47ng.com/docs/debugging)

It will log an error if multiple context references are loaded.

**Comment by pluvrt** [comment]
In case anybody is still encountering this:

TLDR:
I resolved this by installing `@babel/core` as a `devDependency` in each monorepo package `nuqs` was installed.

Longer:
I'm using pnpm with turborepo. When I checked my `pnpm-lock.yaml` file, I found that I had 2 `nuqs` in there due to different  optional dependencies. One had an import path containing `@babel/core` and the other did not. This was happening even though I had never directly installed `@babel/core` as a dependency.

```yml
  nuqs@2.3.2(next@15.1.7(@babel/core@7.26.8)(react-dom@19.0.0(react@19.0.0))(react@19.0.0))(react@19.0.0):
    dependencies:
      mitt: 3.0.1
      react: 19.0.0
    optionalDependencies:
      next: 15.1.7(@babel/core@7.26.8)(react-dom@19.0.0(react@19.0.0))(react@19.0.0)

  nuqs@2.3.2(next@15.1.7(react-dom@19.0.0(react@19.0.0))(react@19.0.0))(react@19.0.0):
    dependencies:
      mitt: 3.0.1
      react: 19.0.0
    optionalDependencies:
      next: 15.1.7(react-dom@19.0.0(react@19.0.0))(react@19.0.0)
```

The `NuqsAdapter` I initialized in my root `layout.tsx` was pulling from the one containing `@babel/core`, but other parts of the codebase were pulling from the `nuqs` that did not contain `@babel/core`.

For now, I have decided to manually install `@babel/core` as a `devDependency` in each of the packages where I am installing `nuqs` so that only 1 `nuqs` package is listed in my `pnpm-lock.yaml`. This appears to have resolved the issue for me for now.

**Comment by olafurns7** [comment]
I have this same issue in a turborepo monorepo, all the dependencies in pnpm-lock are the same, so its not an issue of mis-aligned dependencies I believe.

They all look like this:

```
next: 14.2.21(@babel/core@7.26.7)(@opentelemetry/api@1.8.0)(@playwright/test@1.48.0)(react-dom@18.3.1(react@18.3.1))(react@18.3.1)

  nuqs@2.3.2(next@14.2.21(@babel/core@7.26.7)(@opentelemetry/api@1.9.0)(@playwright/test@1.48.0)(react-dom@18.3.1(react@18.3.1))(react@18.3.1))(react@18.3.1):
    dependencies:
      mitt: 3.0.1
      react: 18.3.1
    optionalDependencies:
      next: 14.2.21(@babel/core@7.26.7)(@opentelemetry/api@1.9.0)(@playwright/test@1.48.0)(react-dom@18.3.1(react@18.3.1))(react@18.3.1)
```

**Comment by janglad** [comment]
I ended up creating a package just from nuqs with a simple `export * from nuqs`, then use that across my monorepo. Not the most elegant but did end up solving the issue.

**Comment by franky47** [comment]
I doubt it's the case, but I'm wondering if this could be due to `catalog:react19` being left out in the published package.json's devDependencies, causing pnpm to duplicate references on install. I'll try a build with those references resolved and will post it here.

**Comment by franky47** [comment]
I managed to reproduce this issue in a monorepo (PNPM) setup with:
- A `ui` library that defines components using nuqs hooks
- A Next.js app using the `nuqs/adapters/next/app` adapter
- A React Router v7 using the `nuqs/adapters/react-router/v7` adapter

The interesting thing is that the React Router app works perfectly fine, but Next.js exhibits this error, and the debugging helper in #861 is not actually helping in that case.

I'll keep investigating.

**Comment by franky47** [comment]
I had a [quick chat](https://bsky.app/profile/francoisbest.com/post/3llk3ai33vk2g) with @tkdodo who has a similar thread on React Query, maybe y'all can find some solutions there:

https://github.com/TanStack/query/issues/3595

**Comment by himself65** [comment]
I think I have the same error

**Comment by himself65** [comment]
<img width="1194" alt="Image" src="https://github.com/user-attachments/assets/cd809e56-b063-4278-976f-0958c28777f1" />

pnpm install two version of nuqs for some reasons. IDK

**Comment by pluvrt** [comment]
> <img width="1194" alt="Image" src="https://github.com/user-attachments/assets/cd809e56-b063-4278-976f-0958c28777f1" />
> 
> pnpm install two version of nuqs for some reasons. IDK

It looks to me that your pnpm is installing two versions of next.js. Sure they have the same semver, but they are pointing to different versions of @babel/core making them separate modules in your lock-file.

**Comment by marko-hologram** [comment]
I know this thread mostly mentions monorepo setups, but we ran into this issue with a published package that was being consumed by another app. On a project I work on, we publish a custom package to a private registry and that then can be consumed by multiple applications. Issue was that nuqs was being bundled into the published package, but we also wanted to use nuqs inside the app itself so it was also installed there as well.

One option was to re-export nuqs from that published package so that it gets bundled and then consumed from there, but I didn't like that idea very much. Since we use Vite to build that package, I added nuqs to `rollupOptions.external` property on Vite config.

```ts
external: ["react", "react-dom", "react/jsx-runtime", "nuqs"],
```

That ensured nuqs wasn't being bundled into the published package and that version that was consumed by the package that was the version being installed into the app that is consuming the package.

Reference docs: https://vite.dev/guide/build.html#library-mode

![Image](https://github.com/user-attachments/assets/6a71b193-fced-4298-a414-d1275f6cb832)

I'm writing this in case somebody runs into the same issue as we did because we got the error mentioned here even though we weren't using nuqs in a monorepo.

**Comment by marko-hologram** [comment]
> Thanks [@marko-hologram](https://github.com/marko-hologram), this is something [I wrote about on Bluesky](https://bsky.app/profile/francoisbest.com/post/3llk3ahconk2g), but that could maybe be a video or a blog post of its own: how to write & publish libraries that use nuqs' hooks & features.
> 
> TL;DR:
> 
> > Issue was that nuqs was being bundled into the published package
> 
> You'll always want to add nuqs as a peer dependency of your published packages, with the semver range that makes sense for the features you use (usually sticking to a major version should be good enough).

> You'll always want to add nuqs as a peer dependency of your published packages

It wasn't just that. I did add it as a peer dependency into package.json, but because it was being used inside the package directly, it was also being bundled by Vite (rollup). I had to specifically mark it as an "external" dependency so it doesn't get bundled.

I don't have experience with publishing packages so all of this wasn't immediately obvious to me 😄

**Comment by codythatsme** [comment]
Hey all,

This has started happening in my monorepo, with multiple contexts detected. However, in all my package.json the version is locked.

Nowhere for me to mark as peer dep, because we use turborepo internal packages pattern: https://turborepo.com/docs/core-concepts/internal-packages

Any ideas for further troubleshooting would be great.

**Comment by franky47** [comment]
> Nowhere for me to mark as peer dep, because we use turborepo internal packages pattern

In each package that uses nuqs, you could have it as a peerDependency, and the final consuming app would have it as a regular dependency, the method you use to link your own packages to your app should not matter here.

What package manager (and version) are you using?

**Comment by PL-Aufi-Fillah** [comment]
in my case, it was because of different version of next package in each workspace, for example im using `next@15.1.7` on the first workspace and using `next@15.2.3` on the second one and because of that pnpm will create multiple deps for nuqs with different version of next like so:

```
nuqs@2.4.3(next@15.1.7(react-dom@19.0.0(react@19.0.0))(react@19.0.0))(react@19.0.0):
    dependencies:
      mitt: 3.0.1
      react: 19.0.0
    optionalDependencies:
      next: 15.1.7(react-dom@19.0.0(react@19.0.0))(react@19.0.0)

  nuqs@2.4.3(next@15.2.3(react-dom@19.0.0(react@19.0.0))(react@19.0.0))(react@19.0.0):
    dependencies:
      mitt: 3.0.1
      react: 19.0.0
    optionalDependencies:
      next: 15.2.3(react-dom@19.0.0(react@19.0.0))(react@19.0.0)
```

downgrading the second one into `15.1.7` works for me. although I haven't tried to clean installing all the packages but at least I don't have interfere with the lockfile and don't need to install it on the root package, so I guess maybe it'll work for some of u guys
